before_script:
- mkdir -p ~/.ssh
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
- chmod 700 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts

build:
  stage: deploy
  environment: Staging
  image: node:latest
  only:
  - master
  script:
  - yarn install
  - yarn run api:prod
  - yarn run client:prod
  - rsync -av -e ssh --exclude='node_modules' . $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY
  - ssh $MAIN_USER@$SERVER_HOST "cd $APP_DIRECTORY; yarn install"
deploy:
  stage: deploy
  environment: Production
  only:
  - tags
  script:
  - yarn install
  - yarn run api:prod
  - yarn run client:prod
  - rsync -av -e ssh --exclude='node_modules' . $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY
  - ssh $MAIN_USER@$SERVER_HOST "cd $APP_DIRECTORY; yarn install"