before_script:
- mkdir -p ~/.ssh
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
- chmod 700 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts

build:
  stage: deploy
  environment: Staging
  image: node:latest
  only:
  - master
  script:
  - yarn install
  - yarn run api:prod
  - yarn run client:prod
  - scp -o stricthostkeychecking=no -r ./app/client/package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/client
  - scp -o stricthostkeychecking=no -r ./app/client/dist $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/client
  - scp -o stricthostkeychecking=no -r ./app/api/package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/api
  - scp -o stricthostkeychecking=no -r ./app/api/dist $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/api
  - scp -o stricthostkeychecking=no -r ./package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/
  - scp -o stricthostkeychecking=no -r ./app/api/src/Schema/Schema.graphql $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/src/Schema
  - ssh $MAIN_USER@$SERVER_HOST "cd $APP_DIRECTORY; yarn install"
deploy:
  stage: deploy
  environment: Production
  only:
  - tags
  script:
  - yarn install
  - yarn run api:prod
  - yarn run client:prod
  - scp -o stricthostkeychecking=no -r ./app/client/package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/client
  - scp -o stricthostkeychecking=no -r ./app/client/dist $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/client
  - scp -o stricthostkeychecking=no -r ./app/api/package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/api
  - scp -o stricthostkeychecking=no -r ./app/api/dist $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/app/api
  - scp -o stricthostkeychecking=no -r ./package.json $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/
  - scp -o stricthostkeychecking=no -r ./app/api/src/Schema/Schema.graphql $MAIN_USER@$SERVER_HOST:$APP_DIRECTORY/src/Schema
  - ssh $MAIN_USER@$SERVER_HOST "cd $APP_DIRECTORY; yarn install"