version: '3'
services:
  api:
    build: .
    container_name: dashboard_api
    ports:
      - "3030:3030"
      - "4000:4000"
#    command: yarn nodemon app/api/dist/app.js
  db:
    image: "rethinkdb:latest"
    container_name: dashboard_db
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    links:
      - api