version: '3'
services:
  api:
    build: .
    container_name: dashboard_api
    ports:
      - "4000:4000"
    command: yarn nodemon app/api/dist/app.js
  db:
    image: "rethinkdb:latest"
    container_name: dashboard_db
    ports:
      - "8080:8090"
      - "28015:28015"
      - "29015:29015"
    links:
      - api
  client:
    image: traefik
    container_name: dashboard_load_balancer
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock