version: '3'

services:
  reverse-proxy:
    image: traefik
    container_name: dashboard_load_balancer
    command: --api --docker
    ports:
    - "80:80"
    - "8080:8090"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  # BUILD APP
  build:
    build: .
    container_name: dashboard_build_runner
    volumes:
    - dashboard_app:/Dashboard

  # BACKEND
  api:
    image: node:latest
    container_name: dashboard_api
    command: node /Dashboard/api/app.js
    ports:
    - "4000:4000"
    depends_on:
    - build
    volumes:
    - dashboard_app:/Dashboard

  # FRONTEND
  client:
    image: nginx:stable
    container_name: dashboard_client
    command: nginx -c /Dashboard/nginx.conf -g "daemon off;"
    ports:
    - "3030:3030"
    depends_on:
    - build
    volumes:
    - dashboard_app:/Dashboard

  # DATABASE
  db:
    image: rethinkdb:latest
    container_name: dashboard_db
    ports:
    - "8090:8080"
    - "28015:28015"
    - "29015:29015"
    volumes:
    - /usr/app/rethinkdb:/data

volumes:
  dashboard_app: