version: '3'

services:
  # BUILD APP
  build:
    build: .
    container_name: dashboard_build_runner
    volumes:
    - dashboard_app:/Dashboard

  #  # BACKEND
  api:
    image: node:latest
    container_name: dashboard_api
    command: node /Dashboard/api/app.js
    ports:
    - "4000:4000"
    depends_on:
    - build
    volumes:
    - dashboard_app:/Dashboard
    networks:
    - dashboard
    labels:
    - "traefik.backend=DashboardApi"
    - "traefik.docker.network=dashboard"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:api.liquidash.pl"
    - "traefik.port=4000"

  # FRONTEND
  client:
    image: nginx:stable
    container_name: dashboard_client
    command: nginx -c /Dashboard/nginx.conf -g "daemon off;"
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - build
    volumes:
    - dashboard_app:/Dashboard
    networks:
    - dashboard
    labels:
    - "traefik.backend=DashboardClient"
    - "traefik.docker.network=dashboard"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:client.liquidash.pl"
    - "traefik.port=80"
    - "traefik.port=443"

  # DATABASE
  db:
    image: rethinkdb:latest
    container_name: dashboard_db
    command: rethinkdb --http-port 1337 --bind all
    ports:
    - "1337:1337"
    - "28015:28015"
    - "29015:29015"
    volumes:
    - /usr/app/rethinkdb:/data
    networks:
    - dashboard
    labels:
    - "traefik.backend=DashboardDB"
    - "traefik.docker.network=dashboard"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:db.liquidash.pl"
    - "traefik.port=1337"

  # REVERSE PROXY
#  reverse-proxy:
#    image: traefik
#    container_name: dashboard_load_balancer
#    command: --api --docker
#    environment:
#    - DO_AUTH_TOKEN=5a5e783b235ae06fc7df891db38e664415a41bfead49716a635e6f2cbc4602d3
#    ports:
#    - "80:80"
#    - "443:443"
#    - "8080:8080"
#    volumes:
#    - /usr/app/DashboardTS/traefik.toml:/traefik.toml
#    - /var/run/docker.sock:/var/run/docker.sock
#    - /usr/app/DashboardTS/acme.json:/acme.json
#    - /etc/letsencrypt/live/liquidash.pl:/etc/letsencrypt/live/liquidash.pl
#    networks:
#    - dashboard
#    labels:
#    - "traefik.backend=DashboardReverseProxy"
#    - "traefik.docker.network=dashboard"
#    - "traefik.frontend.rule=Host:traefik.liquidash.pl"
#    - "traefik.port=8080"
volumes:
  dashboard_app:
networks:
  dashboard: