
 defaultEntryPoints = ["http", "https"]
#logLevel = "DEBUG"

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

#[file]

[retry]

[api]
    dashboard = true

[docker]
#entrypoint = "traefik"
endpoint = "unix:///var/run/docker.sock"
domain = "liquidash.pl"
watch = true
exposedByDefault = false

[acme]
email = "holgrin@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
provider = "digitalocean"
delayBeforeCheck = 0
#[acme.httpChallenge]
#entryPoint = "http"
[[acme.domains]]
    main = "liquidash.pl"
[[acme.domains]]
    main = "*.liquidash.pl"