
 defaultEntryPoints = ["http", "https"]
#logLevel = "DEBUG"

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            certFile = "/Dashboard/config/fullchain.pem"
            keyFile = "/Dashboard/config/privkey.pem"

[api]
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "liquidash.pl"
watch = true
exposedByDefault = false
#usebindportip = true

#[acme]
#email = "holgrin@gmail.com"
#storage = "acme.json"
#entryPoint = "https"
#onHostRule = true
#onDemand = false
##caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#[acme.dnsChallenge]
#provider = "digitalocean"
#delayBeforeCheck = 0
##[acme.httpChallenge]
##entryPoint = "http"
#[[acme.domains]]
#    main = "liquidash.pl"
#[[acme.domains]]
#    main = "*.liquidash.pl"