
defaultEntryPoints = ["http", "https"]
#logLevel = "DEBUG"

insecureSkipVerify = true

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "/Dashboard/config/fullchain.pem"
keyFile = "/Dashboard/config/privkey.pem"

[api]
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "liquidash.pl"
watch = true
exposedByDefault = false
#usebindportip = true