type Query {
    getUser(login: String): User
}

type Post {
    id: ID
    author: User
    create_date: String
    title: String
    content: String
    likes: [Like]
}

type Like {
    id: ID
    user: User
}

type User {
    id: ID
    avatar: String
    country: String
    email: String
    firstName: String
    language: String
    lastName: String
    login: String
    password: String
}