
defaultEntryPoints = ["http", "https"]

insecureSkipVerify = true

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"
useXForwardedFor = true
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "/Triton/config/cert/fullchain.pem"
keyFile = "/Triton/config/cert/privkey.pem"

[api]
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "liquidash.pl"
watch = true
exposedByDefault = false
